In [3254]:
import pandas as pd

# Albert "Chip" Zecker 

Downloaded the excel files from his committee contributions [here](https://cal-access.sos.ca.gov/Campaign/Candidates/Detail.aspx?id=1463374) (late and all contributions). Adding them together, cleaning and removing duplicates below:

In [3255]:
# import csv 

zecher_late_df = pd.read_csv('./raw_files/zecher_late.csv')

In [3256]:
zecher_late_df.columns = zecher_late_df.columns.str.lower().str.replace(' ', '_')

In [3257]:
print(zecher_late_df.shape)

(57, 12)

In [3258]:
zecher_all_df = pd.read_csv('./raw_files/zecher_all.csv')

In [3259]:
zecher_all_df.shape

(244, 12)

In [3260]:
zecher_all_df.columns = zecher_all_df.columns.str.lower().str.replace(' ', '_')

In [3261]:
zecher_late_df.head()

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,$500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,$500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499

In [3262]:
zecher_all_df.head()

,name_of_contributor,payment_type,city,state,zip,id_number,employer,occupation,amount,transaction_date,filed_date,transaction_number
0,BOSTON PROPERTIES,MONETARY,SAN FRANCISCO,CA,94111,NaN,NaN,NaN,"$10,000.00",1/4/2024,1/25/2024,2873178 - INC208
1,KEVIN BASS,MONETARY,DANVILLE,CA,94526,NaN,ENTERPRISE MOBILITY,VICE PRESIDENT & GENERAL MANAGER,$500.00,1/5/2024,1/25/2024,2873178 - INC209
2,ST JOHN BAIN,MONETARY,SONOMA,CA,95476,NaN,TIMI,"SENIOR DIRECTOR, STRATEGIC PARTNERSHIPS","$3,500.00",1/5/2024,1/25/2024,2873178 - INC210
3,CLAIRE SOLOT,MONETARY,SONOMA,CA,95476,NaN,BIGGLESWORTH FAMILY FOUNDATION,MANAGING DIRECTOR,"$3,500.00",1/5/2024,1/25/2024,2873178 - INC211
4,LAURIE THOMAS,MONETARY,SAN FRANCISCO,CA,94114,NaN,NICE VENTURES INC,PRESIDENT,$500.00,1/6/2024,1/25/2024,2873178 - INC212

In [3263]:
zecher_df = pd.concat([zecher_late_df, zecher_all_df])

In [3264]:
zecher_df["committee_name"] = "ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP"

In [3265]:
zecher_df.head(5)

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,$500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,$500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP

In [3266]:
zecher_df['date'] = pd.to_datetime(zecher_df['transaction_date'], format='%m/%d/%Y')

In [3267]:
zecher_df['amount'] = zecher_df['amount'].str.replace('$', '')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/380300085.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  zecher_df['amount'] = zecher_df['amount'].str.replace('$', '')

In [3268]:
zecher_df['amount'] = zecher_df['amount'].str.replace(',', '')

In [3269]:
zecher_df['amount'] = zecher_df['amount'].astype(float)

In [3270]:
zecher_df['transaction_number'] = zecher_df['transaction_number'].str.replace(' - ', '-')

In [3271]:
zecher_doubles = zecher_df[zecher_df.duplicated(subset=['name_of_contributor', 'amount', 'date', 'transaction_type'], keep=False)]

In [3272]:
zecher_doubles

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
40,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,1/25/2024,2873178-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16
88,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC19,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
96,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC21,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
243,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,2/22/2024,2895288-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16

I have addressed entries that seem like duplicates but are in fact transactions of the same type from the same person on the same day. Now I am looking for duplicates overall based on the name, amount and date.

In [3273]:
zecher_df[zecher_df.duplicated(subset=['name_of_contributor', 'amount', 'date'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
5,REGINA CALLAN,SAN FRANCISCO,CA / 94123,NaN,REGINA CALLAN DESIGN,OWNER,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/13/2024,02/19/2024,2892610-INC441,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-13
6,KEITH WETMORE,NEWPORT BEACH,CA / 92657,NaN,MAJOR LINDSEY AND AFRICA,RECRUITER,2500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/14/2024,02/15/2024,2891799-INC455,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
7,NEIL MEHTA,SAN FRANCISCO,CA / 94115,NaN,GREENOAKS CAPITAL,FOUNDER,49999.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/14/2024,02/15/2024,2891799-INC454,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
8,SUSAN LOWENBERG,SAN FRANCISCO,CA / 94108,NaN,LOWENBERG CORPORATION,REAL ESTATE INVESTOR,1250.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/12/2024,02/13/2024,2890866-INC435,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-12
9,JOYCE NEWSTAT,SAN FRANCISCO,CA / 94108,NaN,ROCKET SCIENCE ASSOCIATES,CHIEF EXECUTIVE OFFICER,1250.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/12/2024,02/13/2024,2890866-INC434,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,NEIL MEHTA,SAN FRANCISCO,NaN,NaN,GREENOAKS CAPITAL,FOUNDER,49999.00,NaN,NaN,2/14/2024,2/22/2024,2895288-INC454,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
235,KEITH WETMORE,NEWPORT BEACH,NaN,NaN,MAJOR LINDSEY AND AFRICA,RECRUITER,2500.00,NaN,NaN,2/14/2024,2/22/2024,2895288-INC455,MONETARY,CA,92657.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
241,NEW TRADITION MEDIA LLC(EVAN RICHHEIMER),NEW YORK,NaN,NaN,NaN,NaN,2708.75,NaN,NaN,2/5/2024,2/22/2024,2895288-NON400,NON-MONETARY,NY,10012.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-05
242,FRED FAVERO,SONOMA,NaN,NaN,FAVERO VINEYARDS,OWNER,2708.75,NaN,NaN,2/5/2024,2/22/2024,2895288-NON401,NON-MONETARY,CA,95476.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-05
243,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.00,NaN,NaN,10/16/2023,2/22/2024,2895288-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16

Also, there are no duplicates just based on the transaction number.

In [3274]:
zecher_df[zecher_df.duplicated(subset=['transaction_number'], keep=False)]

Empty DataFrame
Columns: [name_of_contributor, city, state/zip, id_number, employer, occupation, amount, transaction_type, type, transaction_date, filed_date, transaction_number, payment_type, state, zip, committee_name, date]
Index: []

Here I am actually removing the duplicates:

In [3275]:
zecher_df = zecher_df.drop_duplicates(subset=['name_of_contributor', 'amount', 'date'])

In [3276]:
zecher_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,ED CONLON,SAN FRANCISCO,NaN,NaN,HATHAWAY DINWIDDIE CONSTRUCTION CO.,VICE PRESIDENT,500.0,NaN,NaN,2/14/2024,2/22/2024,2895288-INC456,MONETARY,CA,94133.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
237,PAUL DENNING,SAN FRANCISCO,NaN,NaN,"DENNING & COMPANY, LLC",INVESTMENT BANKER,500.0,NaN,NaN,2/14/2024,2/22/2024,2895288-INC457,MONETARY,CA,94135.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-14
238,ROBERT CHAN,SAN FRANCISCO,NaN,NaN,NONE,RETIRED,300.0,NaN,NaN,2/16/2024,2/22/2024,2895288-INC472,MONETARY,CA,94123.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-16
239,SALLY FAY COTTINGHAM,SAN FRANCISCO,NaN,NaN,NOB HILL GAZETTE,FREELANCE WRITER,250.0,NaN,NaN,2/16/2024,2/22/2024,2895288-INC473,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-16
240,MARYANNE SANGIACOMO,SAN FRANCISCO,NaN,NaN,TRINITY,PRINCIPAL,500.0,NaN,NaN,2/16/2024,2/22/2024,2895288-INC474,MONETARY,CA,94127.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-16

In [3277]:
zecher_df = pd.concat([zecher_df, zecher_doubles])

In [3278]:
zecher_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,MARYANNE SANGIACOMO,SAN FRANCISCO,NaN,NaN,TRINITY,PRINCIPAL,500.0,NaN,NaN,2/16/2024,2/22/2024,2895288-INC474,MONETARY,CA,94127.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-16
40,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,1/25/2024,2873178-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16
88,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC19,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
96,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC21,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
243,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,2/22/2024,2895288-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16

In [3279]:
zecher_df[zecher_df.duplicated(subset=['name_of_contributor', 'amount', 'date'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
40,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,1/25/2024,2873178-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16
88,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC19,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
40,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,1/25/2024,2873178-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16
88,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC19,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
96,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC21,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
243,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,2/22/2024,2895288-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16

In [3280]:
zecher_df = zecher_df.drop_duplicates(subset=['transaction_number'])

In [3281]:
zecher_df[zecher_df.duplicated(subset=['name_of_contributor', 'amount', 'date'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date
40,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,1/25/2024,2873178-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16
88,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC19,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
96,DAVID ZILBERMAN,SAN FRANCISCO,NaN,NaN,NORWEST VENTURE PARTNERS,GENERAL PARTNER,250.0,NaN,NaN,11/3/2023,1/25/2024,2873175-INC21,MONETARY,CA,94115.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-11-03
243,ALBERT ZECHER,SAN FRANCISCO,NaN,NaN,NaN,NaN,0.0,NaN,NaN,10/16/2023,2/22/2024,2895288-PAY9,LOAN,CA,94122.0,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2023-10-16

In [3282]:
zecher_df.shape

(249, 17)

Reading in independent expeditures

In [3283]:
zecher_ind = pd.read_csv('./raw_files/zecher_ind.csv')

In [3284]:
zecher_ind

,date,name_of_contributor,position,amount,description
0,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$17792.50,ONLINE ADS
1,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$3985.77,ONLINE ADS
2,01/26/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$1594.31,ONLINE ADS
3,01/31/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$478.29,DESIGN SERVICES
4,01/21/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$199.28,ONLINE ADS
5,01/24/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$143.48,ONLINE ADS

In [3285]:
zecher_ind['date'] = pd.to_datetime(zecher_ind['date'], format='%m/%d/%Y')

In [3286]:
zecher_ind['amount'] = zecher_ind['amount'].str.replace('$', '')

zecher_ind['amount'] = zecher_ind['amount'].astype(float)

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/1371513256.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  zecher_ind['amount'] = zecher_ind['amount'].str.replace('$', '')

In [3287]:
zecher_ind['committee_name'] = 'Independent Expenditure'

In [3288]:
zecher_ind

,date,name_of_contributor,position,amount,description,committee_name
0,2024-01-30,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,17792.50,ONLINE ADS,Independent Expenditure
1,2024-01-30,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,3985.77,ONLINE ADS,Independent Expenditure
2,2024-01-26,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,1594.31,ONLINE ADS,Independent Expenditure
3,2024-01-31,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,478.29,DESIGN SERVICES,Independent Expenditure
4,2024-01-21,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,199.28,ONLINE ADS,Independent Expenditure
5,2024-01-24,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,143.48,ONLINE ADS,Independent Expenditure

In [3289]:
zecher_df = pd.concat([zecher_df, zecher_ind])

In [3290]:
zecher_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date,position,description
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23,NaN,NaN
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,3985.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,2024-01-30,SUPPORT,ONLINE ADS
2,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,1594.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,2024-01-26,SUPPORT,ONLINE ADS
3,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,478.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,2024-01-31,SUPPORT,DESIGN SERVICES
4,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,199.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,2024-01-21,SUPPORT,ONLINE ADS
5,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,143.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,2024-01-24,SUPPORT,ONLINE ADS

In [3291]:
# add a column called contest that is equal to "zecher"

zecher_df['contest'] = 'zecher'

Begert

In [3292]:
begert_1_late_df = pd.read_csv('./raw_files/begert_1_late.csv')

In [3293]:
begert_2_late_df = pd.read_csv('./raw_files/begert_2_late.csv')

In [3294]:
begert_1_all_df = pd.read_csv('./raw_files/begert_1_all.csv')

In [3295]:
begert_2_all_df = pd.read_csv('./raw_files/begert_2_all.csv')

In [3296]:
begert_1_late_df.columns = begert_1_late_df.columns.str.lower().str.replace(' ', '_')
begert_2_late_df.columns = begert_2_late_df.columns.str.lower().str.replace(' ', '_')
begert_1_all_df.columns = begert_1_all_df.columns.str.lower().str.replace(' ', '_')
begert_2_all_df.columns = begert_2_all_df.columns.str.lower().str.replace(' ', '_')

In [3297]:
begert_1_late_df["committee_name"] = "BEGERT 2024; RETAIN JUDGE MICHAEL"
begert_1_all_df["committee_name"] = "BEGERT 2024; RETAIN JUDGE MICHAEL"
begert_2_late_df["committee_name"] = "BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING THE RETENTION OF JUDGES MICHAEL ISAKU"
begert_2_all_df["committee_name"] ="BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING THE RETENTION OF JUDGES MICHAEL ISAKU"

In [3298]:
begert_1_late_df.head()

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$3,813.96",LATE CONTRIBUTION RECEIVED,INITIAL,02/25/2024,02/26/2024,2897168-NON705,BEGERT 2024; RETAIN JUDGE MICHAEL
1,NEWTON J LAM,SAN RAFAEL,CA / 94903,NaN,NONE,RETIRED,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/23/2024,2895747-INC694,BEGERT 2024; RETAIN JUDGE MICHAEL
2,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$7,500.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2892878-NON661,BEGERT 2024; RETAIN JUDGE MICHAEL
3,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/20/2024,2892878-INC653,BEGERT 2024; RETAIN JUDGE MICHAEL
4,CALIFORNIA ASIAN PACIFIC AMERICAN JUDGES ASSOC...,ALAMEDA,CA / 94501,1402811.0,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/16/2024,2892063-INC652,BEGERT 2024; RETAIN JUDGE MICHAEL

In [3299]:
begert_2_late_df.head()

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name
0,SAN FRANCISCO LEAGUE OF PISSED OFF VOTERS SMO,SAN FRANCISCO,CA / 94110,1432377.0,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,01/31/2024,02/21/2024,2894188-NON298,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
1,DEAN PRESTON,SAN FRANCISCO,CA / 94117,NaN,CITY AND COUNTY OF SAN FRANCISCO,DISTRICT 5 SUPERVISOR,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2893256-INC296,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
2,GAIL DEKREON,SAN FRANCISCO,CA / 94124,NaN,NaN,RETIRED,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/14/2024,02/15/2024,2891868-INC286,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
3,LILAH WOLF,SAN FRANCISCO,CA / 94103,NaN,SAN FRANCISCO PUBLIC DEFENDER'S OFFICE,DEPUTY PUBLIC DEFENDER,"$2,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/06/2024,02/07/2024,2888963-INC265,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
4,JOHN KEKER,SAN FRANCISCO,CA / 94111-1809,NaN,KEKER VAN NEST AND PETERS,ATTORNEY,"$2,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/02/2024,02/05/2024,2886104-INC252,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...

In [3300]:
begert_1_all_df.head()

,name_of_contributor,payment_type,city,state,zip,id_number,employer,occupation,amount,transaction_date,filed_date,transaction_number,committee_name
0,STEVE ROSEN,MONETARY,WEST LAKE HILLS,TX,78746,NaN,THE UNIVERSITY OF TEXAS AT AUSTIN,ATTORNEY,$250.00,1/1/2024,2/21/2024,2873432 - INC312,BEGERT 2024; RETAIN JUDGE MICHAEL
1,DONALD SULLIVAN,MONETARY,MILL VALLEY,CA,94941,NaN,NONE,RETIRED JUDGE,$250.00,1/1/2024,2/21/2024,2873432 - INC313,BEGERT 2024; RETAIN JUDGE MICHAEL
2,LILLIAN SING,MONETARY,SAN FRANCISCO,CA,94122,NaN,NONE,RETIRED,$100.00,1/1/2024,2/21/2024,2873432 - INC314,BEGERT 2024; RETAIN JUDGE MICHAEL
3,ANTHONY MCNAMER,MONETARY,PORTLAND,OR,97214,NaN,NONE,RETIRED,$200.00,1/1/2024,2/21/2024,2873432 - INC316,BEGERT 2024; RETAIN JUDGE MICHAEL
4,CHRIS CANNON,MONETARY,TIBURON,CA,94920,NaN,SELF-EMPLOYED; SAME NAME,LAWYER,$100.00,1/1/2024,2/21/2024,2873432 - INC317,BEGERT 2024; RETAIN JUDGE MICHAEL

In [3301]:
begert_2_all_df.head()

,name_of_contributor,payment_type,city,state,zip,id_number,employer,occupation,amount,transaction_date,filed_date,transaction_number,committee_name
0,MERIDEE MOORE,MONETARY,SAN FRANCISCO,CA,94118,NaN,"WATERSHED ASSET MANAGEMENT, LLC",SENIOR MANAGING MEMBER,$250.00,1/13/2024,1/25/2024,2872960 - INC100,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
1,WILLIAM OSTERHOUDT,MONETARY,SAN FRANCISCO,CA,94108,NaN,OSTERHOUDT LAW,LAWYER,$250.00,1/13/2024,1/25/2024,2872960 - INC101,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
2,WILLIAM WILSON,MONETARY,HALF MOON BAY,CA,94019,NaN,HAYNES AND BOONE LLP,LAWYER,$250.00,1/15/2024,1/25/2024,2872960 - INC102,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
3,ALLEN RUBY,MONETARY,SARATOGA,CA,95070,NaN,ALLEN RUBY,LAWYER,"$1,000.00",1/15/2024,1/25/2024,2872960 - INC103,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...
4,WARD PENFOLD,MONETARY,KENSINGTON,CA,94707,NaN,LATHAM & WATKINS LLP,ATTORNEY,"$1,000.00",1/16/2024,1/25/2024,2872960 - INC104,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...

In [3302]:
# concatenate the dataframes

begert_df = pd.concat([begert_1_late_df, begert_2_late_df, begert_1_all_df, begert_2_all_df])

In [3303]:
begert_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$3,813.96",LATE CONTRIBUTION RECEIVED,INITIAL,02/25/2024,02/26/2024,2897168-NON705,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN
1,NEWTON J LAM,SAN RAFAEL,CA / 94903,NaN,NONE,RETIRED,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/23/2024,2895747-INC694,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN
2,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$7,500.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2892878-NON661,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN
3,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/20/2024,2892878-INC653,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN
4,CALIFORNIA ASIAN PACIFIC AMERICAN JUDGES ASSOC...,ALAMEDA,CA / 94501,1402811.0,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/16/2024,2892063-INC652,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,$500.00,NaN,NaN,2/13/2024,2/22/2024,2895026 - INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,$250.00,NaN,NaN,2/12/2024,2/22/2024,2895026 - INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,$500.00,NaN,NaN,2/15/2024,2/22/2024,2895026 - INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111
132,GAIL DEKREON,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,"$1,000.00",NaN,NaN,2/14/2024,2/22/2024,2895026 - INC286,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94124
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,$150.00,NaN,NaN,2/13/2024,2/22/2024,2895026 - INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117

In [3304]:
begert_df['date'] = pd.to_datetime(begert_df['transaction_date'], format='%m/%d/%Y')

In [3305]:
begert_df['amount'] = begert_df['amount'].str.replace('$', '')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/3088740851.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  begert_df['amount'] = begert_df['amount'].str.replace('$', '')

In [3306]:
begert_df['amount'] = begert_df['amount'].str.replace(',', '')

In [3307]:
begert_df['amount'] = begert_df['amount'].astype(float)

In [3308]:
begert_df['transaction_number'] = begert_df['transaction_number'].str.replace(' - ', '-')

In [3309]:
begert_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,3813.96,LATE CONTRIBUTION RECEIVED,INITIAL,02/25/2024,02/26/2024,2897168-NON705,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-25
1,NEWTON J LAM,SAN RAFAEL,CA / 94903,NaN,NONE,RETIRED,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/23/2024,2895747-INC694,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-23
2,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,7500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2892878-NON661,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-18
3,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/20/2024,2892878-INC653,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16
4,CALIFORNIA ASIAN PACIFIC AMERICAN JUDGES ASSOC...,ALAMEDA,CA / 94501,1402811.0,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/16/2024,2892063-INC652,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104,2024-02-13
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.00,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118,2024-02-12
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.00,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111,2024-02-15
132,GAIL DEKREON,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,1000.00,NaN,NaN,2/14/2024,2/22/2024,2895026-INC286,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94124,2024-02-14
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-13

In [3310]:
begert_df[begert_df.duplicated(subset=['name_of_contributor', 'amount', 'date','transaction_type'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
25,VIDHYA PRABHAKARAN,SAN FRANCISCO,CA / 94127,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,01/08/2024,01/08/2024,2865105-INC354,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-01-08
27,VIDHYA PRABHAKARAN,SAN FRANCISCO,CA / 94127,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,01/08/2024,01/09/2024,2865506-INC91,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,NaN,NaN,NaN,2024-01-08
36,VIDHYA PRABHAKARAN,SAN FRANCISCO,NaN,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,1000.0,NaN,NaN,1/8/2024,2/21/2024,2873432-INC354,BEGERT 2024; RETAIN JUDGE MICHAEL,MONETARY,CA,94127,2024-01-08
112,MICHAEL BEGERT,PIEDMONT,NaN,NaN,SUPERIOR COURT OF SAN FRANCISCO COUNTY,JUDGE,0.0,NaN,NaN,10/18/2023,2/21/2024,2873432-PAY17,BEGERT 2024; RETAIN JUDGE MICHAEL,LOAN,CA,94611,2023-10-18
400,MICHAEL BEGERT,PIEDMONT,NaN,NaN,SUPERIOR COURT OF SAN FRANCISCO COUNTY,JUDGE,0.0,NaN,NaN,10/18/2023,2/21/2024,2893895-PAY17,BEGERT 2024; RETAIN JUDGE MICHAEL,LOAN,CA,94611,2023-10-18
68,VIDHYA PRABHAKARAN,SAN FRANCISCO,NaN,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,1000.0,NaN,NaN,1/8/2024,1/25/2024,2872960-INC91,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94127,2024-01-08

Checked these on PDFs, they are duplicates. Vidhya only donated once.

In [3311]:
begert_df = begert_df.drop_duplicates(subset=['date', 'amount', 'name_of_contributor'])

In [3312]:
begert_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,3813.96,LATE CONTRIBUTION RECEIVED,INITIAL,02/25/2024,02/26/2024,2897168-NON705,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-25
1,NEWTON J LAM,SAN RAFAEL,CA / 94903,NaN,NONE,RETIRED,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/23/2024,2895747-INC694,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-23
2,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,7500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2892878-NON661,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-18
3,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/20/2024,2892878-INC653,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16
4,CALIFORNIA ASIAN PACIFIC AMERICAN JUDGES ASSOC...,ALAMEDA,CA / 94501,1402811.0,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/16/2024,2892063-INC652,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,HARRIS TABACK,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF HARRIS TABACK,ATTORNEY,250.00,NaN,NaN,2/11/2024,2/22/2024,2895026-INC269,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-11
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104,2024-02-13
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.00,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118,2024-02-12
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.00,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111,2024-02-15
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-13

In [3313]:
begert_df[begert_df.duplicated(subset=['transaction_number'], keep=False)]

Empty DataFrame
Columns: [name_of_contributor, city, state/zip, id_number, employer, occupation, amount, transaction_type, type, transaction_date, filed_date, transaction_number, committee_name, payment_type, state, zip, date]
Index: []

In [3314]:
begert_df['contest'] = 'begert'

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/653920462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  begert_df['contest'] = 'begert'

In [3315]:
begert_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date,contest
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,3813.96,LATE CONTRIBUTION RECEIVED,INITIAL,02/25/2024,02/26/2024,2897168-NON705,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-25,begert
1,NEWTON J LAM,SAN RAFAEL,CA / 94903,NaN,NONE,RETIRED,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/23/2024,2895747-INC694,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-23,begert
2,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,7500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2892878-NON661,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-18,begert
3,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/20/2024,2892878-INC653,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16,begert
4,CALIFORNIA ASIAN PACIFIC AMERICAN JUDGES ASSOC...,ALAMEDA,CA / 94501,1402811.0,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/16/2024,2892063-INC652,BEGERT 2024; RETAIN JUDGE MICHAEL,NaN,NaN,NaN,2024-02-16,begert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,HARRIS TABACK,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF HARRIS TABACK,ATTORNEY,250.00,NaN,NaN,2/11/2024,2/22/2024,2895026-INC269,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-11,begert
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104,2024-02-13,begert
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.00,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118,2024-02-12,begert
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.00,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111,2024-02-15,begert
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.00,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-13,begert

Roland

In [3316]:
roland_late_df = pd.read_csv('./raw_files/roland_late.csv')

In [3317]:
roland_all_df = pd.read_csv('./raw_files/roland_all.csv')

In [3318]:
roland_late_df["committee_name"] = "ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYUNGJIN"
roland_all_df["committee_name"] = "ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYUNGJIN"

In [3319]:
roland_late_df.columns = roland_late_df.columns.str.lower().str.replace(' ', '_')
roland_all_df.columns = roland_all_df.columns.str.lower().str.replace(' ', '_')

In [3320]:
roland_df = pd.concat([roland_late_df, roland_all_df])

In [3321]:
roland_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip
0,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,"$9,516.45",LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON445,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN
1,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,"$17,500.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON444,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN
2,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,"$5,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC443,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN
3,AS&P CORPORATION,UNION CITY,CA / 94587,NaN,NaN,NaN,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC442,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN
4,TIMOTHY MARKS,SAN FRANCISCO,CA / 94108,NaN,"TUCKER AND MARKS, INC.",MANAGING PRINCIPAL,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2894178-INC413,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,CYRUS SANANDAJI,SAN FRANCISCO,NaN,NaN,PRESIDIO BAY VENTURES,MANAGING PRINCIPAL,$500.00,NaN,NaN,1/12/2024,1/25/2024,2873353 - INC223,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94111.0
221,MARK CONROE,SAN FRANCISCO,NaN,NaN,PRESIDIO DEVELOPMENT PARTNERS LLC,REAL ESTATE DEVELOPER,$100.00,NaN,NaN,1/11/2024,1/25/2024,2873353 - INC224,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94123.0
222,HOLLY PETERSON,SAN FRANCISCO,NaN,NaN,NONE,RETIRED,$500.00,NaN,NaN,1/11/2024,1/25/2024,2873353 - INC225,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94118.0
223,ALLISON ESPESETH,SAN FRANCISCO,NaN,NaN,SELF-EMPLOYED/SAME NAME,STRATEGIC MARKETING CONSULTANT,$100.00,NaN,NaN,1/11/2024,1/25/2024,2873353 - INC226,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94115.0
224,TANGUY SERRA,SAN FRANCISCO,NaN,NaN,GOODFINCH,INVESTOR,$100.00,NaN,NaN,1/11/2024,1/25/2024,2873353 - INC228,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94115.0

In [3322]:
roland_df['date'] = pd.to_datetime(roland_df['transaction_date'], format='%m/%d/%Y')

In [3323]:
roland_df['amount'] = roland_df['amount'].str.replace('$', '')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/542461781.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  roland_df['amount'] = roland_df['amount'].str.replace('$', '')

In [3324]:
roland_df['amount'] = roland_df['amount'].str.replace(',', '')

In [3325]:
roland_df['amount'] = roland_df['amount'].str.replace('(', '-')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/1733581832.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  roland_df['amount'] = roland_df['amount'].str.replace('(', '-')

In [3326]:
roland_df['amount'] = roland_df['amount'].str.replace(')', '')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/1961913788.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  roland_df['amount'] = roland_df['amount'].str.replace(')', '')

In [3327]:
roland_df['amount'] = roland_df['amount'].astype(float)

In [3328]:
roland_df['transaction_number'] = roland_df['transaction_number'].str.replace(' - ', '-')

In [3329]:
roland_df[roland_df.duplicated(subset=['name_of_contributor', 'amount', 'date','transaction_type'], keep=False)]

Empty DataFrame
Columns: [name_of_contributor, city, state/zip, id_number, employer, occupation, amount, transaction_type, type, transaction_date, filed_date, transaction_number, committee_name, payment_type, state, zip, date]
Index: []

In [3330]:
roland_df[roland_df.duplicated(subset=['name_of_contributor', 'amount', 'date'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
7,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,35000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/18/2024,2892486-NON409,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-16
8,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,31303.86,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/18/2024,2892486-NON408,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-16
9,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,10201.80,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/18/2024,2892486-NON407,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-16
10,GFC COURAGE COMMITTEE - SIERRA CHAPTER,SAN RAFAEL,CA / 94901,1416442.0,NaN,NaN,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/18/2024,2892486-INC377,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-16
11,SAN FRANCISCO POLICE OFFICERS ASSOCIATION PAC,SAN FRANCISCO,CA / 94103,1315969.0,NaN,NaN,20000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/16/2024,02/18/2024,2892486-INC376,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,DANA SPILIOTIS,SAN FRANCISCO,NaN,NaN,SELF-EMPLOYED/SAME NAME,TECHNOLOGY ADVISOR/INVESTOR,2500.00,NaN,NaN,12/18/2023,1/25/2024,2873352-INC162,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94115.0,2023-12-18
188,STANLEE GATTI,SAN FRANCISCO,NaN,NaN,STANLEE R GATTI DESIGNS,DESIGNER,2000.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC181,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94103.0,2024-01-11
189,KEVIN HARTZ,SAN FRANCISCO,NaN,NaN,A* CAPITAL,CO-FOUNDER/GENERAL PARTNER,10000.00,NaN,NaN,1/12/2024,1/25/2024,2873353-INC182,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94133.0,2024-01-12
190,WILLIAM S FISHER,REDWOOD CITY,NaN,NaN,MANZANITA CAPITAL,INVESTOR,1000.00,NaN,NaN,1/19/2024,1/25/2024,2873353-INC189,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94065.0,2024-01-19
208,SIG ANDERMAN,SAN FRANCISCO,NaN,NaN,NONE,RETIRED,2000.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC208,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94111.0,2024-01-11

In [3331]:
roland_df = roland_df.drop_duplicates(subset=['date', 'amount', 'name_of_contributor'])

In [3332]:
roland_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
0,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,9516.45,LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON445,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-22
1,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,17500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON444,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-22
2,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC443,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-21
3,AS&P CORPORATION,UNION CITY,CA / 94587,NaN,NaN,NaN,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC442,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-21
4,TIMOTHY MARKS,SAN FRANCISCO,CA / 94108,NaN,"TUCKER AND MARKS, INC.",MANAGING PRINCIPAL,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2894178-INC413,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,CYRUS SANANDAJI,SAN FRANCISCO,NaN,NaN,PRESIDIO BAY VENTURES,MANAGING PRINCIPAL,500.00,NaN,NaN,1/12/2024,1/25/2024,2873353-INC223,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94111.0,2024-01-12
221,MARK CONROE,SAN FRANCISCO,NaN,NaN,PRESIDIO DEVELOPMENT PARTNERS LLC,REAL ESTATE DEVELOPER,100.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC224,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94123.0,2024-01-11
222,HOLLY PETERSON,SAN FRANCISCO,NaN,NaN,NONE,RETIRED,500.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC225,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94118.0,2024-01-11
223,ALLISON ESPESETH,SAN FRANCISCO,NaN,NaN,SELF-EMPLOYED/SAME NAME,STRATEGIC MARKETING CONSULTANT,100.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC226,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94115.0,2024-01-11
224,TANGUY SERRA,SAN FRANCISCO,NaN,NaN,GOODFINCH,INVESTOR,100.00,NaN,NaN,1/11/2024,1/25/2024,2873353-INC228,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,MONETARY,CA,94115.0,2024-01-11

Add the independent expenditures:

In [3333]:
roland_ind = pd.read_csv("./raw_files/roland_ind.csv")

In [3334]:
roland_ind

,date,name_of_contributor,position,amount,description
0,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$15713.49,ONLINE ADS
1,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$3520.05,ONLINE ADS
2,01/26/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$1408.02,ONLINE ADS
3,01/31/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$422.41,DESIGN SERVICES
4,01/21/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$176.00,ONLINE ADS
5,01/24/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$126.72,ONLINE ADS

In [3335]:
roland_ind['committee_name'] = 'Independent Expenditure'

In [3336]:
roland_ind

,date,name_of_contributor,position,amount,description,committee_name
0,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$15713.49,ONLINE ADS,Independent Expenditure
1,01/30/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$3520.05,ONLINE ADS,Independent Expenditure
2,01/26/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$1408.02,ONLINE ADS,Independent Expenditure
3,01/31/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$422.41,DESIGN SERVICES,Independent Expenditure
4,01/21/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$176.00,ONLINE ADS,Independent Expenditure
5,01/24/2024,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,SUPPORT,$126.72,ONLINE ADS,Independent Expenditure

In [3337]:
roland_ind['amount'] = roland_ind['amount'].str.replace('$', '')

roland_ind['amount'] = roland_ind['amount'].astype(float)

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/3750798406.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  roland_ind['amount'] = roland_ind['amount'].str.replace('$', '')

In [3338]:
roland_ind['date'] = pd.to_datetime(roland_ind['date'], format='%m/%d/%Y')

In [3339]:
roland_df = pd.concat([roland_df, roland_ind])

In [3340]:
roland_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date,position,description
0,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,9516.45,LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON445,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-22,NaN,NaN
1,CHIP ZECHER FOR SUPERIOR COURT JUDGE 2024,SAN FRANCISCO,CA / 94118,1463380.0,NaN,NaN,17500.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/22/2024,02/22/2024,2895403-NON444,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-22,NaN,NaN
2,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC443,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-21,NaN,NaN
3,AS&P CORPORATION,UNION CITY,CA / 94587,NaN,NaN,NaN,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895403-INC442,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-21,NaN,NaN
4,TIMOTHY MARKS,SAN FRANCISCO,CA / 94108,NaN,"TUCKER AND MARKS, INC.",MANAGING PRINCIPAL,1000.00,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2894178-INC413,ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYU...,NaN,NaN,NaN,2024-02-20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,3520.05,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,NaN,NaN,NaN,2024-01-30,SUPPORT,ONLINE ADS
2,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,1408.02,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,NaN,NaN,NaN,2024-01-26,SUPPORT,ONLINE ADS
3,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,422.41,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,NaN,NaN,NaN,2024-01-31,SUPPORT,DESIGN SERVICES
4,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,176.00,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,NaN,NaN,NaN,2024-01-21,SUPPORT,ONLINE ADS
5,COALITION TO GROW SAN FRANCISCO - GROW SF PAC,NaN,NaN,NaN,NaN,NaN,126.72,NaN,NaN,NaN,NaN,NaN,Independent Expenditure,NaN,NaN,NaN,2024-01-24,SUPPORT,ONLINE ADS

In [3341]:
roland_df['contest'] = 'roland'

Thompson

In [3342]:
# read csv 

thompson_1_late_df = pd.read_csv('./raw_files/thompson_1_late.csv')
thompson_1_all_df = pd.read_csv('./raw_files/thompson_1_all.csv')
thompson_2_late_df = pd.read_csv('./raw_files/thompson_2_late.csv')
thompson_2_all_df = pd.read_csv('./raw_files/thompson_2_all.csv')

In [3343]:
thompson_1_late_df["committee_name"] = "THOMPSON 2024; RETAIN JUDGE PATRICK"
thompson_1_all_df["committee_name"] = "THOMPSON 2024; RETAIN JUDGE PATRICK"
thompson_2_late_df["committee_name"] = "BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING THE RETENTION OF JUDGES MICHAEL ISAKU"
thompson_2_all_df["committee_name"] = "BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING THE RETENTION OF JUDGES MICHAEL ISAKU"

In [3344]:
thompson_1_all_df

,NAME OF CONTRIBUTOR,PAYMENT TYPE,CITY,STATE,ZIP,ID NUMBER,EMPLOYER,OCCUPATION,AMOUNT,TRANSACTION DATE,FILED DATE,TRANSACTION NUMBER,committee_name
0,RONALD SABRAW,MONETARY,FREMONT,CA,94539,NaN,NaN,RETIRED,($250.00),12/31/2023,1/30/2024,2877631 - EXP151,THOMPSON 2024; RETAIN JUDGE PATRICK
1,MARK DICKSON,MONETARY,SAN MATEO,CA,94402-3989,NaN,PHASE M LEGAL,PATENT ATTORNEY,$200.00,12/28/2023,1/30/2024,2877631 - INC111,THOMPSON 2024; RETAIN JUDGE PATRICK
2,TREVOR READ,MONETARY,SYRACUSE,IN,46567,NaN,AGISTIX,PRESIDENT,$250.00,12/29/2023,1/30/2024,2877631 - INC112,THOMPSON 2024; RETAIN JUDGE PATRICK
3,SALLY ROSENBLATT,MONETARY,SAN FRANCISCO,CA,94129,NaN,NaN,RETIRED,$250.00,12/28/2023,1/30/2024,2877631 - INC113,THOMPSON 2024; RETAIN JUDGE PATRICK
4,JOHN CORTIS,MONETARY,WALNUT CREEK,CA,94595,NaN,NaN,NOT EMPLOYED,$100.00,12/31/2023,1/30/2024,2877631 - INC123,THOMPSON 2024; RETAIN JUDGE PATRICK
...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,LISA DEWBERRY,MONETARY,REDWOOD CITY,CA,94061,NaN,LISA DEWBERRY,ATTORNEY,$100.00,2/14/2024,2/22/2024,2895024 - INC515,THOMPSON 2024; RETAIN JUDGE PATRICK
218,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,NON-MONETARY,OAKLAND,CA,94607,1464402.0,NaN,NaN,"$5,000.00",1/29/2024,2/22/2024,2895024 - NON294,THOMPSON 2024; RETAIN JUDGE PATRICK
219,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,NON-MONETARY,OAKLAND,CA,94607,1464402.0,NaN,NaN,"$23,250.00",2/2/2024,2/22/2024,2895024 - NON406,THOMPSON 2024; RETAIN JUDGE PATRICK
220,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,NON-MONETARY,OAKLAND,CA,94607,1464402.0,NaN,NaN,"$4,012.35",2/3/2024,2/22/2024,2895024 - NON407,THOMPSON 2024; RETAIN JUDGE PATRICK
221,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,NON-MONETARY,OAKLAND,CA,94607,1464402.0,NaN,NaN,"$18,743.02",2/8/2024,2/22/2024,2895024 - NON455,THOMPSON 2024; RETAIN JUDGE PATRICK

In [3345]:
thompson_1_late_df.columns = thompson_1_late_df.columns.str.lower().str.replace(' ', '_')
thompson_1_all_df.columns = thompson_1_all_df.columns.str.lower().str.replace(' ', '_')
thompson_2_late_df.columns = thompson_2_late_df.columns.str.lower().str.replace(' ', '_')
thompson_2_all_df.columns = thompson_2_all_df.columns.str.lower().str.replace(' ', '_')

In [3346]:
thompson_df = pd.concat([thompson_1_late_df, thompson_1_all_df, thompson_2_late_df, thompson_2_all_df])

In [3347]:
thompson_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897219-NON611,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN
1,MICHAEL GLASER,SAN FRANCISCO,CA / 94131,NaN,MORRISON AND FOERSTER LLP,ATTORNEY,"$10,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/24/2024,02/26/2024,2897219-INC609,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN
2,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/24/2024,02/26/2024,2897219-INC608,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN
3,VIDHYA PRABHAKARAN,SAN FRANCISCO,CA / 94127,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,"$1,000.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897219-INC588,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN
4,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,"$7,500.00",LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2893253-NON560,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,$500.00,NaN,NaN,2/13/2024,2/22/2024,2895026 - INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,$250.00,NaN,NaN,2/12/2024,2/22/2024,2895026 - INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,$500.00,NaN,NaN,2/15/2024,2/22/2024,2895026 - INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111
132,GAIL DEKREON,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,"$1,000.00",NaN,NaN,2/14/2024,2/22/2024,2895026 - INC286,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94124
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,$150.00,NaN,NaN,2/13/2024,2/22/2024,2895026 - INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117

In [3348]:
thompson_df['amount'] = thompson_df['amount'].str.replace('$', '')
thompson_df['amount'] = thompson_df['amount'].str.replace('(', '-')
thompson_df['amount'] = thompson_df['amount'].str.replace(')', '')
thompson_df['amount'] = thompson_df['amount'].str.replace(',', '')

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/108440448.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  thompson_df['amount'] = thompson_df['amount'].str.replace('$', '')
/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/108440448.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  thompson_df['amount'] = thompson_df['amount'].str.replace('(', '-')
/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_1433/108440448.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  thompson_df['amount'] = thompson_df['amount'].str.replace(')', '')

In [3349]:
thompson_df['amount'] = thompson_df['amount'].astype(float)

In [3350]:
thompson_df['date'] = pd.to_datetime(thompson_df['transaction_date'], format='%m/%d/%Y')

In [3351]:
thompson_df['transaction_number'] = thompson_df['transaction_number'].str.replace(' - ', '-')

In [3352]:
thompson_df[thompson_df.duplicated(subset=['name_of_contributor', 'amount', 'date','transaction_type'], keep=False)]

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
47,RUTH PACE,ATLANTA,GA / 30309,NaN,NaN,NOT EMPLOYED,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,12/12/2023,12/22/2023,2862266-INC26,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2023-12-12
48,RUTH PACE,ATLANTA,GA / 30309,NaN,NaN,NOT EMPLOYED,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,12/12/2023,12/22/2023,2862266-INC25,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2023-12-12
37,RUTH PACE,ATLANTA,NaN,NaN,NaN,NOT EMPLOYED,1000.0,NaN,NaN,12/12/2023,1/30/2024,2877631-INC25,THOMPSON 2024; RETAIN JUDGE PATRICK,MONETARY,GA,30309,2023-12-12
38,RUTH PACE,ATLANTA,NaN,NaN,NaN,NOT EMPLOYED,1000.0,NaN,NaN,12/12/2023,1/30/2024,2877631-INC26,THOMPSON 2024; RETAIN JUDGE PATRICK,MONETARY,GA,30309,2023-12-12
72,RONALD SABRAW,FREMONT,NaN,NaN,NaN,RETIRED,250.0,NaN,NaN,12/23/2023,1/30/2024,2877631-INC63,THOMPSON 2024; RETAIN JUDGE PATRICK,MONETARY,CA,94539,2023-12-23
73,RONALD SABRAW,FREMONT,NaN,NaN,NaN,RETIRED,250.0,NaN,NaN,12/23/2023,1/30/2024,2877631-INC64,THOMPSON 2024; RETAIN JUDGE PATRICK,MONETARY,CA,94539,2023-12-23

manually going to fix Ruth's contributions below by adding one back, she donated $2,000 total on the 12 and 13 ($1,000 installments) in December. Ronald is the one who returned $250 so this will fix itself

In [3353]:
thompson_df = thompson_df.drop_duplicates(subset=['date', 'amount', 'name_of_contributor'])

In [3354]:
thompson_df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,committee_name,payment_type,state,zip,date
0,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897219-NON611,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2024-02-23
1,MICHAEL GLASER,SAN FRANCISCO,CA / 94131,NaN,MORRISON AND FOERSTER LLP,ATTORNEY,10000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/24/2024,02/26/2024,2897219-INC609,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2024-02-24
2,MATTHEW GRAY,SAN FRANCISCO,CA / 94115,NaN,PERKINS COIE LLP,ATTORNEY,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/24/2024,02/26/2024,2897219-INC608,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2024-02-24
3,VIDHYA PRABHAKARAN,SAN FRANCISCO,CA / 94127,NaN,DAVIS WRIGHT TREMAINE LLP,ATTORNEY,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897219-INC588,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2024-02-23
4,SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING ...,OAKLAND,CA / 94607,1464402.0,NaN,NaN,7500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/18/2024,02/20/2024,2893253-NON560,THOMPSON 2024; RETAIN JUDGE PATRICK,NaN,NaN,NaN,2024-02-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,HARRIS TABACK,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF HARRIS TABACK,ATTORNEY,250.0,NaN,NaN,2/11/2024,2/22/2024,2895026-INC269,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-11
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94104,2024-02-13
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.0,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94118,2024-02-12
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.0,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94111,2024-02-15
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,MONETARY,CA,94117,2024-02-13

In [3355]:
# show the rows where the name is ruth pace 

thompson_df[thompson_df['name_of_contributor'] == 'RUTH PACE']

# duplicate this row

thompson_df = pd.concat([thompson_df, thompson_df[thompson_df['name_of_contributor'] == 'RUTH PACE']])

note: that needs to be fixed later to have the correct transaction number

In [3356]:
thompson_df['contest'] = 'thompson'

### Adding everything together

In [3357]:
df = pd.concat([zecher_df, begert_df, roland_df, thompson_df])

In [3358]:
df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date,position,description,contest
0,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23,NaN,NaN,zecher
1,JEANNIE SANGIACOMO,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
2,WALTER WOOD,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
3,PG&E CORPORATION,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
4,TUCKER AND MARKS INC,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20,NaN,NaN,zecher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,DICK GROSBOLL,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,MONETARY,CA,94104,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson
130,MEGAN JANIS,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.0,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,MONETARY,CA,94118,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-12,NaN,NaN,thompson
131,DANIEL WEINSTEIN,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.0,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,MONETARY,CA,94111,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-15,NaN,NaN,thompson
133,STUART HANLON,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,MONETARY,CA,94117,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson
47,RUTH PACE,ATLANTA,GA / 30309,NaN,NaN,NOT EMPLOYED,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,12/12/2023,12/22/2023,2862266-INC26,NaN,NaN,NaN,THOMPSON 2024; RETAIN JUDGE PATRICK,2023-12-12,NaN,NaN,thompson

In [3359]:
df['name_of_contributor'] = df['name_of_contributor'].str.title()

In [3360]:
df.payment_type.value_counts()

MONETARY        1097
LOAN               5
NON-MONETARY       2
Name: payment_type, dtype: int64

In [3361]:
df = df[df.payment_type != 'Loan']

df = df[df.payment_type != 'NON-MONETARY']

In [3362]:
df

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,filed_date,transaction_number,payment_type,state,zip,committee_name,date,position,description,contest
0,Jeannie Sangiacomo,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,02/26/2024,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23,NaN,NaN,zecher
1,Jeannie Sangiacomo,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/26/2024,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
2,Walter Wood,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
3,Pg&E Corporation,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,02/22/2024,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher
4,Tucker And Marks Inc,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,02/21/2024,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20,NaN,NaN,zecher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,Dick Grosboll,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC274,MONETARY,CA,94104,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson
130,Megan Janis,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.0,NaN,NaN,2/12/2024,2/22/2024,2895026-INC275,MONETARY,CA,94118,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-12,NaN,NaN,thompson
131,Daniel Weinstein,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.0,NaN,NaN,2/15/2024,2/22/2024,2895026-INC285,MONETARY,CA,94111,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-15,NaN,NaN,thompson
133,Stuart Hanlon,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.0,NaN,NaN,2/13/2024,2/22/2024,2895026-INC287,MONETARY,CA,94117,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson
47,Ruth Pace,ATLANTA,GA / 30309,NaN,NaN,NOT EMPLOYED,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,12/12/2023,12/22/2023,2862266-INC26,NaN,NaN,NaN,THOMPSON 2024; RETAIN JUDGE PATRICK,2023-12-12,NaN,NaN,thompson

In [3366]:
df.groupby('committee_name').amount.sum()

committee_name
BEGERT 2024; RETAIN JUDGE MICHAEL                                                                                   346492.07
BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTABLE SAN FRANCISCO SUPPORTING THE RETENTION OF JUDGES MICHAEL ISAKU    284954.40
Independent Expenditure                                                                                              45560.32
ROLAND FOR SUPERIOR COURT JUDGE 2024; JEAN MYUNGJIN                                                                 384889.60
THOMPSON 2024; RETAIN JUDGE PATRICK                                                                                 203275.52
ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP                                                                          680490.33
Name: amount, dtype: float64

In [3369]:
df.columns

Index(['name_of_contributor', 'city', 'state/zip', 'id_number', 'employer',
       'occupation', 'amount', 'transaction_type', 'type', 'transaction_date',
       'filed_date', 'transaction_number', 'payment_type', 'state', 'zip',
       'committee_name', 'date', 'position', 'description', 'contest'],
      dtype='object')

In [3371]:
df['seat'] = df['contest']

In [3372]:
df["seat"].replace({"zecher": "Seat 1", "begert": "Seat 1", "roland": "Seat 13", "thom"}, inplace=True)

,name_of_contributor,city,state/zip,id_number,employer,occupation,amount,transaction_type,type,transaction_date,...,transaction_number,payment_type,state,zip,committee_name,date,position,description,contest,seat
0,Jeannie Sangiacomo,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/23/2024,...,2897128-INC515,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-23,NaN,NaN,zecher,zecher
1,Jeannie Sangiacomo,ROSS,CA / 94957,NaN,NONE,RETIRED,500.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,...,2897128-INC504,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher,zecher
2,Walter Wood,LOS ALTOS,CA / 94022,NaN,NONE,RETIRED,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,...,2895281-INC507,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher,zecher
3,Pg&E Corporation,OAKLAND,CA / 94612,NaN,NaN,NaN,5000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/21/2024,...,2895281-INC506,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-21,NaN,NaN,zecher,zecher
4,Tucker And Marks Inc,SAN FRANCISCO,CA / 94108,NaN,NaN,NaN,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,02/20/2024,...,2893914-INC499,NaN,NaN,NaN,ZECHER FOR SUPERIOR COURT JUDGE 2024; CHIP,2024-02-20,NaN,NaN,zecher,zecher
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,Dick Grosboll,SAN FRANCISCO,NaN,NaN,NEYHART ANDERSON FLYNN GROSBOLL,ATTORNEY,500.0,NaN,NaN,2/13/2024,...,2895026-INC274,MONETARY,CA,94104,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson,thompson
130,Megan Janis,SAN FRANCISCO,NaN,NaN,ABBOTT LABORATORIES,COMPLIANCE OFFICER,250.0,NaN,NaN,2/12/2024,...,2895026-INC275,MONETARY,CA,94118,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-12,NaN,NaN,thompson,thompson
131,Daniel Weinstein,SAN FRANCISCO,NaN,NaN,NaN,RETIRED,500.0,NaN,NaN,2/15/2024,...,2895026-INC285,MONETARY,CA,94111,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-15,NaN,NaN,thompson,thompson
133,Stuart Hanlon,SAN FRANCISCO,NaN,NaN,LAW OFFICE OF STUART HANLON,CRIMINAL DEFENSE ATTORNEY,150.0,NaN,NaN,2/13/2024,...,2895026-INC287,MONETARY,CA,94117,BEGERT AND PATRICK THOMPSON; SAFE AND ACCOUNTA...,2024-02-13,NaN,NaN,thompson,thompson
47,Ruth Pace,ATLANTA,GA / 30309,NaN,NaN,NOT EMPLOYED,1000.0,LATE CONTRIBUTION RECEIVED,INITIAL,12/12/2023,...,2862266-INC26,NaN,NaN,NaN,THOMPSON 2024; RETAIN JUDGE PATRICK,2023-12-12,NaN,NaN,thompson,thompson

In [ ]:
# rename name_of_contributor to name

df = df.rename(columns={'name_of_contributor': 'name', })

In [3368]:
df = df[['name', 'amount', 'committee_name', 'position', 'contest', 'slate', 'race']]

KeyError: "['name', 'slate', 'race'] not in index"